language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - clang-3.5
      - libstdc++-4.9-dev
      - g++-4.9
      - liblua5.1-0-dev
      - lua5.1
      - libboost-dev
    sources:
      - llvm-toolchain-precise-3.5
      - ubuntu-toolchain-r-test

install:
  - if [ "$CXX" == "g++"  ]; then export CXX="g++-4.9"; fi
  - if [ "$CXX" == "clang++"  ]; then export CXX="clang++-3.5"; fi
script:
  - mkdir -p build && cd build/ && cmake .. && make && make install
  - echo "os.exit()" | lua -l color_coded
  - make color_coded_test || true
